### ISSUE TITLE
Upgrade causes alignment issues

### ISSUE THREAD

**Issue by Nick1oo7** [live627/smf-custom-forms#43]
When going from 2x to 4x (including 4.05) upon opening an existing form, previously created, the alignment of the fields is no longer consistent. Some fields align right, some left.  SMF 2.1

**Comment by live627** [comment]
can you add a screenshot?

**Comment by Nick1oo7** [comment]
Apologies, please also note, that this "error" is only on the form when it is being filled out. After the form is submitted and goes to the post, the result is shown properly aligned.

**Comment by live627** [comment]
The field isn't showing its input field. What type? Information?

**Comment by Nick1oo7** [comment]
Does this help?
<img width="1523" alt="Screenshot 2023-05-04 at 07 15 53" src="https://user-images.githubusercontent.com/132328711/236189590-7f8050ab-0e2a-467a-8cba-99b68e051455.png">

**Comment by live627** [comment]
yes it does. Now can you show a screenshot of the  fields in the database?
The table is smf_cf_fields

**Comment by Nick1oo7** [comment]
The form we're looking at is ID 11

<img width="1176" alt="Screenshot 2023-05-04 at 07 41 47" src="https://user-images.githubusercontent.com/132328711/236193965-285d9cd7-21f4-4c14-9315-55c6d093cbf9.png">

**Comment by live627** [comment]
very helpful, thanks. fix incoming.
